apiVersion: edbpostgres.com/v1alpha1
kind: EDBPostgres
metadata:
  name: edb-pg-12
spec:
  # ---------------------------------
  # IMPORTANT: In this CR you will find an example of all options and possible configurations.
  # However, by default values are applied by the operator if values are not specified below.
  # ---------------------------------

  # ---------------------------------
  # ## Default Setup
  # ---------------------------------

  clusterSize: 3
  databaseMemoryLimit: "2Gi"
  databaseMemoryRequest: "1Gi"
  databaseCPULimit: "1000m"
  databaseCPU: "50m"
  databaseStorageRequest: "5Gi"
  databaseStorageClass: "edb-storageclass"
  databaseArchiveStorageClass: "edb-storageclass"
  databaseWalStorageClass: "edb-storageclass"
  databasePort: 5432
  serviceAccount: "edb-operator"
  containerImagePullPolicy: Always
  noRedwoodCompat: false
  highAvailability:
    enable: false
    image:  "quay.io/edb/stolon:v1-ubi7-amd64"
    podDebug: "false"
  # The imaged used in this project is from Red Hat. See more in https://docs.okd.io/latest/using_images/db_images/postgresql.html
  image: "quay.io/edb/postgresql-12:ubi7-amd64"
  secretName: "edb-pg-as12-secret"
  postgresType: "PG"
  postgresVersion: 12
  primaryConfig:
    max_connections: "150"
  customLabels:
    environment: sandbox
    developer: oscar
  customAnnotations:
    maker: omh
    operator_vendor: edb
