apiVersion: edbpostgres.com/v1alpha1
kind: EDBPostgres
metadata:
  name: edb-epas-12
spec:
  clusterSize: 3
  databaseMemoryLimit: "2Gi"
  databaseMemoryRequest: "1Gi"
  databaseCPULimit: "1000m"
  databaseCPU: "50m"
  databaseStorageRequest: "5Gi"
  databaseStorageClass: "edb-storageclass"
  databaseArchiveStorageClass: "edb-storageclass"
  databaseWalStorageClass: "edb-storageclass"
  databasePort: 5444
  serviceAccount: "edb-operator"
  containerImagePullPolicy: Always
  noRedwoodCompat: false
  highAvailability:
    enable: true
    image:  "quay.io/edb/stolon:latest"
    podDebug: "false"
  image: "quay.io/edb/postgres-advanced-server-12:latest"
  secretName: "example-pg-secret"
  postgresType: "AS"
  postgresVersion: 12
  primaryConfig:
    max_connections: "150"
  customLabels:
    environment: development
    developer: edb
  customAnnotations:
    maker: edb
    operator_vendor: edb
  pgExporter:
    enable: true
    image: quay.io/edb/pgxexporter:latest
    command: ["/usr/local/bin/pgx_exporter"]
    args: ["--enableHAMetrics=true","--log.level=debug"]
    secretName: edb-exporter-secret-as
    extendedQueryConfigMap: edb-monitoring-stats
    imagePullPolicy: Always
