apiVersion: edbpostgres.com/v1alpha1
kind: EDBPostgres
metadata:
  name: edb-pg-12-ha
spec:
  clusterSize: 3
  databaseMemoryLimit: "2Gi"
  databaseMemoryRequest: "1Gi"
  databaseCPULimit: "1000m"
  databaseCPU: "50m"
  databaseStorageRequest: "5Gi"
  databaseStorageClass: "edb-storageclass"
  databaseArchiveStorageClass: "edb-storageclass"
  databaseWalStorageClass: "edb-storageclass"
  databasePort: 5432
  containerImagePullPolicy: Always
  serviceAccount: "edb-operator"
  highAvailability:
    enable: true
    image:  "quay.io/edb/stolon:latest"
    podDebug: "true"
  image: "quay.io/edb/postgresql-12:latest"
  secretName: "example-pg-secret"
  postgresType: "PG"
  postgresVersion: 12
  customLabels:
    environment: development
    developer: edb
  customAnnotations:
    maker: edb
    operator_vendor: edb
