# Name of the Kubernetes statefulset and service. Change as desired
name: edb-epas-v11-redwood-statefulset
label: edb-epas11

serviceAccountName: edb-helm
imagePullSecrets: quay-regsecret

acceptEULA: "No"

image: "quay.io/edb/postgres-advanced-server-11:latest"

pgconfig:
  port: 5444

deploymentType: Statefulset

users:
  pgUser: "enterprisedb"
  pgPassword: "edb"

config:
  noRedwoodCompat: false
  customConfigmap: "edb-helm-db-custom-config"

persistence:
  accessModes:
  - ReadWriteOnce
  storageClass: "edb-storageclass"

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 1
    memory: 500Mi
  dataSize: 5Gi
  walSize: 5Gi
  archiveSize: 5Gi
