# Name of the Kubernetes statefulset and service. Change as desired
name: edb-epas-12
label: edb-epas12

serviceAccountName: edb-helm
imagePullSecrets: quay-regsecret

acceptEULA: "No"

image: "quay.io/edb/postgres-advanced-server-12:latest"

pgconfig:
  port: 5444

deploymentType: Statefulset

users:
  secretName: example-pg-secret

config:
  noRedwoodCompat: false
  
persistence:
  accessModes:
  - ReadWriteOnce
  storageClass: "edb-storageclass"

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 1
    memory: 500Mi
  dataSize: 5Gi
  walSize: 5Gi
  archiveSize: 5Gi
