# Name of the Kubernetes statefulset and service.
name: edb-pg-v12-single
label: edb-pg12

serviceAccountName: edb-helm
imagePullSecrets: quay-regsecret

acceptEULA: "No"

image: "quay.io/edb/postgresql-12:latest"

pgconfig:
  port: 5432

users:
  pgUser: "enterprisedb"
  pgPassword: "edb"

deploymentType: Pod

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 1
    memory: 500Mi
  dataSize: 5Gi
  walSize: 5Gi
  archiveSize: 5Gi
