---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: edb-epas11-redwood
  name: edb-epas-v11-redwood-statefulset 
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5444
    protocol: TCP
    targetPort: 5444
  selector:
    app: edb-epas11-redwood
    statefulset.kubernetes.io/pod-name: edb-epas-v11-redwood-statefulset-0 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: edb-epas-v11-redwood-statefulset 
spec:
  selector:
    matchLabels:
      app: edb-epas11-redwood
  serviceName: edb-epas-v11-redwood-statefulset 
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: edb-epas11-redwood
    spec:
      serviceAccountName: edb-cli
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: quay-regsecret
      containers:
        - name: edb-database
          image: "quay.io/edb/postgres-advanced-server-11:latest"
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["-ec", "/police.sh && /launch.sh"]
          env:
            - name: PG_INITDB
              value: "true"
            - name: PG_USER
              value: enterprisedb
            - name: PG_PASSWORD
              value: edb
            - name: PGDATA
              value: /var/lib/edb/data
            - name: PGDATA_WAL
              value: /var/lib/edb/wal
            - name: PGDATA_ARCHIVE
              value: /var/lib/edb/wal_archive
            - name: USE_CONFIGMAP
              value: "true"
            - name: NO_REDWOOD_COMPAT
              value: "false"
            - name: CHARSET
              value: UTF8
          ports:
            - name: postgres
              containerPort: 5444
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 5444
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 5444
          resources:
            limits:
              memory: 1Gi
              cpu: 2
            requests:
              memory: 500Mi
              cpu: 1
          volumeMounts:
            - name: data
              mountPath: /var/lib/edb/data
            - name: wal
              mountPath: /var/lib/edb/wal
            - name: walarchive
              mountPath: /var/lib/edb/wal_archive
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: edb-cli-db-custom-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: wal
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: walarchive
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
