---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: edb-pg11
  name: edb-pg-v11-statefulset
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: edb-pg11
    statefulset.kubernetes.io/pod-name: edb-pg-v11-statefulset-0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: edb-pg-v11-statefulset
spec:
  selector:
    matchLabels:
      app: edb-pg11
  serviceName: edb-pg-v11-statefulset 
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: edb-pg11
    spec:
      serviceAccountName: edb-cli
      imagePullSecrets:
      - name: quay-regsecret
      terminationGracePeriodSeconds: 10
      containers:
        - name: edb-database
          image: "quay.io/edb/postgresql-11:latest"
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["-ec", "/police.sh && /launch.sh"]
          env:
            - name: PG_INITDB
              value: "true"
            - name: USE_SECRET
              value: "true"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: my-pg-secret
                  key: pgUser
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-pg-secret
                  key: pgPassword
            - name: PGDATA
              value: /var/lib/edb/data
            - name: PGDATA_WAL
              value: /var/lib/edb/wal
            - name: PGDATA_ARCHIVE
              value: /var/lib/edb/wal_archive
            - name: USE_CONFIGMAP
              value: "false"
            - name: CHARSET
              value: UTF8
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 5432
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 5432
          resources:
            limits:
              memory: 1Gi
              cpu: 2
            requests:
              memory: 500Mi
              cpu: 1
          volumeMounts:
            - name: data
              mountPath: /var/lib/edb/data
            - name: wal
              mountPath: /var/lib/edb/wal
            - name: walarchive
              mountPath: /var/lib/edb/wal_archive
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: edb-storageclass
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: wal
      spec:
        storageClassName: edb-storageclass
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: walarchive
      spec:
        storageClassName: edb-storageclass
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
