---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: edb-pg11-single
  name: edb-pg-v11-single
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: edb-pg11-single
---
apiVersion: v1
kind: Pod
metadata:
  name: edb-pg-v11-single
  labels:
    app: edb-pg11-single
spec:
  serviceAccountName: edb
  containers:
    - name: edb-database
      image: "quay.io/edb/postgresql-11:latest"
      imagePullPolicy: Always
      command: ["/bin/bash"]
      args: ["-ec", "/police.sh && /launch.sh"]
      env:
        - name: PG_INITDB
          value: "true"
        - name: PG_USER
          value: enterprisedb
        - name: PG_PASSWORD
          value: edb
        - name: PGDATA
          value: /var/lib/edb/data
        - name: PGDATA_WAL
          value: /var/lib/edb/wal
        - name: PGDATA_ARCHIVE
          value: /var/lib/edb/wal_archive
        - name: USE_CONFIGMAP
          value: "true"
        - name: CHARSET
          value: UTF8
      ports:
        - name: postgres
          containerPort: 5432
          protocol: TCP
      livenessProbe:
        initialDelaySeconds: 10
        periodSeconds: 10
        tcpSocket:
          port: 5432
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 10
        tcpSocket:
          port: 5432
      resources:
        limits:
          memory: 1Gi
          cpu: 2
        requests:
          memory: 500Mi
          cpu: 1
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: edb-db-custom-config
