---
apiVersion: v1
kind: Service
metadata:
  labels:
    # Use the same label for all parts of the application.
    app: edb-epas12-noredwood-single
  # This sets the name of the service. Can be different than the name of the statefulset.
  name: edb-epas-v12-noredwood-single
spec:
  # This can be changed to allow for external trafic.
  # As an alternative for external connectivity look at Jaeger or Traefik.
  type: ClusterIP
  ports:
  - name: postgres
    # Change this to have the service listen on another port.
    port: 5444
    protocol: TCP
    # For PostgreSQL pods set this to 5432.
    targetPort: 5444
  selector:
    # This needs to conform to the label of the statefulset.
    app: edb-epas12-noredwood-single
---
apiVersion: v1
kind: Pod
metadata:
  # This sets the name of the statefulset. Can be different than the name of the service.
  name: edb-epas-v12-noredwood-single
  labels:
    # Use the same label for all parts of the application.
    app: edb-epas12-noredwood-single
spec:
  # The service account used for deploying the pods.
  # The service account should have sufficient permissions.
  serviceAccountName: edb
  containers:
    - name: edb-database
      # This can be set to another image. Images can be found in:
      # quay.io/enterprisedb/postgres{10,11,12}-advanced-server
      # quay.io/enterprisedb/postgresql(10,11,12}
      image: "quay.io/enterprisedb/postgres12-advanced-server:latest"
      # Pull a new version of the container on every reschedule of the pod.
      imagePullPolicy: Always
      command: ["/bin/bash"]
      args: ["-ec", "/police.sh && /launch.sh"]
      env:
        - name: PG_USER
          # The initial superuser of the cluster.
          value: enterprisedb
        - name: PG_PASSWORD
          # The password of PG_USER.
          value: edb
        - name: PGDATA
          # Location of the datafiles.
          value: /var/lib/edb/data
        - name: PGDATA_WAL
          # Location of the walfiles.
          value: /var/lib/edb/wal
        - name: PGDATA_ARCHIVE
          # Location of the archive files.
          value: /var/lib/edb/wal_archive
        - name: NO_REDWOOD_COMPAT
          # Disable redwood compatibility options on EDB Postgres Advanced Server.
          value: "true"
        - name: CHARSET
          # The initial charactset of the cluster.
          value: UTF8
      ports:
        - name: postgres
          # The Port that is exposed on these pods. Set to 5432 for Postgres.
          containerPort: 5444
          protocol: TCP
      livenessProbe:
        initialDelaySeconds: 10
        periodSeconds: 10
        tcpSocket:
          port: 5444
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 10
        tcpSocket:
          port: 5444
      resources:
        limits:
          # Set this to configure the max amount of memory available to the container.
          memory: 1Gi
          # Set this to configure the max amount of cpu available to the container.
          cpu: 2
        requests:
          # Set this to configure the memory shares available to the container under pressure.
          memory: 500Mi
          # Set this to configure the cpu hares available to the container under pressure.
          cpu: 1
