version: '3'

services:
  edb-postgres:
    command: bash -c '/police.sh && /launch.sh'
    image: quay.io/edb/postgresql-12:latest
    container_name: edb-postgres
    network_mode: bridge
    environment:
      - PG_INITDB=true
      - PG_PASSWORD=mypassword
      - PGDATA=/data
    volumes:
      - pgdata:/data


volumes:
  pgdata:
    external: true
