version: '3'
services:
  edb-postgres:
    command: bash -c '/police.sh && /launch.sh'
    image: quay.io/edb/postgresql-12:latest
    container_name: edb-postgres
    environment:
      - PG_INITDB=true
      - PG_PASSWORD=mypassword
