apiVersion: apps/v1
kind: Deployment
metadata:
  name: edb-operator
spec:
  replicas: 2 
  selector:
    matchLabels:
      name: edb-operator
  template:
    metadata:
      labels:
        name: edb-operator
    spec:
      serviceAccountName: edb-operator
      containers:
        - name: edb-operator
          # Replace this with the built image name
          image: quay.io/edb/edb-operator:latest
          command:
            - edb-operator
          args:
            - "--metrics-addr=127.0.0.1:8080"
            - "--enable-leader-election"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "edb-operator"
          livenessProbe:
            httpGet:
              path: /alive
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 8081
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
        - name: quay-regsecret # This should be replace by the docker repository secret to pull the image
