# this is the name of the statefulset and service. It defaults to image
name: edb-as-v11-noredwood
label: edb-as11-noredwood

acceptEULA: "Yes"

config:
  noRedwoodCompat: "true"
  customConfigmap: "edb-db-custom-config"

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 1
    memory: 500Mi
  dataSize: 5Gi
  walSize: 5Gi
  archiveSize: 5Gi
