apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "edb.label" . }}
  name: {{ .Values.name }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: postgres
    port: {{ .Values.pgconfig.port }}
    protocol: TCP
    targetPort: {{ .Values.pgconfig.port }}
  selector:
    app: {{ template "edb.label" . }}
    {{- if eq .Values.deploymentType "Statefulset" }}
    statefulset.kubernetes.io/pod-name: {{ .Values.name }}-0
    {{- end }}
